---
openapi: 3.0.3
servers:
  - url: /api/auth
info:
  title: UserService API
  version: '1.0.0'
tags:
  - name: User
paths:
  /register:
    post:
      tags:
        - User
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponse"
  /login:
    post:
      tags:
        - User
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
                
components:
  schemas:
    RegisterRequest:
      required:
        - email
        - password
        - name
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string
    RegisterResponse:
      required:
        - token
      type: object
      properties:
        token:
          type: string
    LoginRequest:
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    LoginResponse:
      required:
        - token
      type: object
      properties:
        token:
          type: string
   